services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="videos-api"
    volumes:
      - transcoder_mongodb_data:/data/db
    ports:
      - 27017:27017
  minio:
    image: minio/minio
    entrypoint: sh
    # create the 'videos' bucket before starting the service
    command: -c 'mkdir -p /data/videos && minio server --address ":9000" --console-address ":9001" /data'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - '9090:9000'
      - '9091:9001'
    volumes:
      - transcoder_minio_data:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s

volumes:
  transcoder_minio_data:
    driver: local
  transcoder_mongodb_data:
    driver: local
